Categories:
  - Recipe Manager
License: GPL-3.0-only
WebSite: https://brassica.crispilly.de
SourceCode: https://github.com/crispilly/brassica
IssueTracker: https://github.com/crispilly/brassica/issues
Changelog: https://github.com/crispilly/brassica/releases

AuthorName: Crispilly
AuthorWebSite: https://brassica.crispilly.de
AutoName: Brassica

RepoType: git
Repo: https://github.com/crispilly/brassica.git
Binaries: https://github.com/crispilly/brassica/releases/download/v%v/Brassica-Android-%v.apk

Builds:
  - versionName: 2.0.6
    versionCode: 2000600
    commit: 28b3051d43f8acc5b2f9bf75c9f7f8698db15e5b
    subdir: android
    gradle:
      - fdroid

AllowedAPKSigningKeys: 6a7dc30b8ca7b74be4d5cb11354c16bef358c172fa7ec3703b61b8e6a5b159c2

AutoUpdateMode: Version
UpdateCheckMode: Tags ^v[\d.]+$
CurrentVersion: 2.0.6
CurrentVersionCode: 2000600
